-- This file intentionally left empty.
-- lazy.nvim loads all *.lua files in lua/plugins/ automatically.
-- Plugin specs are split across:
--   colorscheme.lua  – catppuccin theme
--   ui.lua           – neo-tree, lualine, bufferline, which-key, trouble
--   telescope.lua    – fuzzy finder
--   treesitter.lua   – syntax / text objects
--   lsp.lua          – mason, LSP, typescript-tools, cmp, lint, format
--   git.lua          – gitsigns, neogit, diffview
--   debug.lua        – nvim-dap + codelldb for C++
--   editor.lua       – autopairs, comments, surround, ts-autotag
return {}
